# Generated by Django 5.2.4 on 2025-07-15 18:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UPZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upzs', to='bache.localidad')),
            ],
            options={
                'unique_together': {('localidad', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('upz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrios', to='bache.upz')),
            ],
            options={
                'unique_together': {('upz', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Bache',
            fields=[
                ('estado', models.CharField(choices=[('sin_arreglar', 'Sin Arreglar'), ('en_proceso', 'En Proceso'), ('arreglado', 'Arreglado')], default='sin_arreglar', max_length=100)),
                ('peligrosidad', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], default='Bajo', max_length=100)),
                ('tipo_calle', models.CharField(choices=[('Calle', 'Calles'), ('Carrera', 'Carreras'), ('Avenida', 'Avenidas'), ('Transversal', 'Transversales'), ('Diagonal', 'Diagonales'), ('Callejones', 'Callejones')], default='Calle', max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=20, max_digits=25, verbose_name='latitud')),
                ('longitud', models.DecimalField(decimal_places=20, max_digits=25, verbose_name='longitud')),
                ('diametro', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='diametro')),
                ('accidentes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('foto', models.ImageField(help_text='Suba una imagen clara del accidente (Formatos permitidos: JPG, JPEG, PNG)', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Fotografía del incidente')),
                ('id_bache', models.CharField(editable=False, help_text='Identificador único con formato BHC seguido de 5 letras mayúsculas (excluyendo I y O)', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID del Bache')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baches', to='bache.barrio')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baches', to='bache.localidad')),
                ('upz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baches', to='bache.upz')),
            ],
            options={
                'verbose_name': 'Bache',
                'verbose_name_plural': 'Baches',
                'ordering': ['id_bache'],
            },
        ),
    ]
