# Generated by Django 5.2.4 on 2025-07-31 00:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='pdfs/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('fecha_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_logout', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Cédula o Nombre de Usuario')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('localidad', models.CharField(max_length=100)),
                ('ciudad_origen', models.CharField(max_length=100, verbose_name='Ciudad de Origen')),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Teléfono')),
                ('medio_trans', models.CharField(max_length=100, verbose_name='Medio de Transporte')),
                ('email', models.EmailField(max_length=254)),
                ('notificacion', models.BooleanField(default=False, verbose_name='¿Desea recibir notificaciones?')),
                ('rol', models.IntegerField(verbose_name='Rol del Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_request', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID de Solicitud')),
                ('tipo', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(verbose_name='Fecha de Solicitud')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', verbose_name='Cédula o Nombre de Usuario')),
            ],
        ),
    ]
