# Generated by Django 5.2.4 on 2025-07-20 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Cédula o Nombre de Usuario')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('localidad', models.CharField(max_length=100)),
                ('medio_trans', models.CharField(max_length=100, verbose_name='Medio de Transporte')),
                ('email', models.EmailField(max_length=254)),
                ('notificacion', models.BooleanField(default=False, verbose_name='¿Desea recibir notificaciones?')),
                ('rol', models.IntegerField(verbose_name='Rol del Usuario')),
            ],
        ),
    ]
