# Generated by Django 5.2.4 on 2025-07-22 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('username_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', verbose_name='Cédula o Nombre de Usuario')),
            ],
        ),
    ]
