# Generated by Django 5.2.4 on 2025-07-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosesion',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
