# Generated by Django 5.2.4 on 2025-08-28 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_documento_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='La cédula debe tener entre 5 y 10 dígitos numéricos.', regex='^\\d{5,10}$')], verbose_name='Cédula o Nombre de Usuario'),
        ),
    ]
