# Generated by Django 5.2.4 on 2025-07-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='id_request',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID de Solicitud'),
        ),
    ]
