# Generated by Django 5.2.4 on 2025-07-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_registrosesion_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosesion',
            name='duracion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
