# Generated by Django 5.2.4 on 2025-08-01 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_registrosesion_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosesion',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', verbose_name='Cédula o Nombre de Usuario'),
        ),
    ]
