# Generated by Django 5.2.4 on 2025-07-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_servicio_id_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='username_cedula',
            new_name='cedula',
        ),
    ]
