# Generated by Django 5.2.4 on 2025-07-22 19:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import reportes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bache', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_report', models.CharField(default=reportes.models.generar_id_reporte, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('involucrado_reporte', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('senializacion_presente', models.BooleanField(default=False)),
                ('licencia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_emergencia', models.PositiveIntegerField(default=0)),
                ('matricula_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('compania_aseguradora', models.BooleanField(default=False)),
                ('id_seguro_aseguradora', models.CharField(blank=True, max_length=100, null=True)),
                ('testigos', models.PositiveIntegerField(default=0)),
                ('heridos', models.PositiveIntegerField(default=0)),
                ('datos_testigos', models.CharField(blank=True, max_length=200, null=True)),
                ('datos_heridos', models.CharField(blank=True, max_length=200, null=True)),
                ('tiempo_respuesta_policia', models.DurationField(blank=True, null=True)),
                ('tiempo_respuesta_grua', models.DurationField(blank=True, null=True)),
                ('tiempo_respuesta_aseguradora', models.DurationField(blank=True, null=True)),
                ('tiempo_respuesta_bomberos', models.DurationField(blank=True, null=True)),
                ('tiempo_respuesta_medicos', models.DurationField(blank=True, null=True)),
                ('parte_policial', models.BooleanField(default=False)),
                ('id_parte_policial', models.CharField(blank=True, max_length=100, null=True)),
                ('danio_fisico_personal', models.BooleanField(default=False)),
                ('reclamo_formal', models.BooleanField(default=False)),
                ('abogado_presente', models.BooleanField(default=False)),
                ('vehiculos_afectados', models.PositiveIntegerField(default=0)),
                ('datos_vehiculos', models.CharField(blank=True, max_length=100, null=True)),
                ('danios_ambiente', models.BooleanField(default=False)),
                ('conocimeinto_tenia', models.BooleanField(default=False)),
                ('estado_problema_vehiculo', models.BooleanField(default=False)),
                ('foto1', models.ImageField(help_text='Suba una imagen clara del accidente (Formatos permitidos: JPG, JPEG, PNG)', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Fotografía del incidente')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Fotografía del incidente 2')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Fotografía del incidente 3')),
                ('bache', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='bache.bache')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='usuario.usuario')),
            ],
        ),
    ]
